@php
    $saved = $section?->toArray() ?? [];
    $submitted = old('form_key') === $formKey ? old() : [];
    $value = fn ($key, $default = '') => data_get($submitted, $key, data_get($saved, $key, $default));
    $consumers = $section?->consumers->keyBy('category') ?? collect();
    $consumerValue = fn ($category, $key) => data_get($submitted, 'consumers.'.$category.'.'.$key, data_get($consumers->get($category), $key, ''));
@endphp
<input type="hidden" name="form_key" value="{{ $formKey }}"><input type="hidden" name="revision" value="{{ $batch->revision }}">
<div class="mdb-fields">
    <label>Start waypoint reference<input name="start_reference" value="{{ $value('start_reference') }}" maxlength="100" required data-copy-key="start_reference"><small>Text reference; leading zeros are preserved.</small></label>
    <label>End waypoint reference<input name="end_reference" value="{{ $value('end_reference') }}" maxlength="100" required data-copy-key="end_reference"></label>
    <label>Start GPX source file<select name="start_source_file_id" data-copy-key="start_source_file_id"><option value="">Unresolved source</option>@foreach($batch->sources->where('kind', 'gpx') as $source)<option value="{{ $source->id }}" @selected((string) $value('start_source_file_id') === (string) $source->id)>{{ $source->original_name }} v{{ $source->version }}</option>@endforeach</select></label>
    <label>End GPX source file<select name="end_source_file_id" data-copy-key="end_source_file_id"><option value="">Unresolved source</option>@foreach($batch->sources->where('kind', 'gpx') as $source)<option value="{{ $source->id }}" @selected((string) $value('end_source_file_id') === (string) $source->id)>{{ $source->original_name }} v{{ $source->version }}</option>@endforeach</select></label>
    <label>Exact start waypoint, if ambiguous<select name="start_waypoint_id"><option value="">Resolve by text reference and source file</option>@foreach($batch->sources->where('kind', 'gpx') as $source)@foreach($source->waypoints as $point)<option value="{{ $point->id }}" @selected((string) $value('start_waypoint_id') === (string) $point->id)>#{{ $point->id }} {{ $point->name }} | {{ $source->original_name }} v{{ $source->version }} | {{ $point->latitude }}, {{ $point->longitude }}{{ $point->recorded_at ? ' | '.$point->recorded_at->timezone('Asia/Karachi')->format('d M Y H:i:s').' PKT' : '' }}</option>@endforeach @endforeach</select><small>The exact point must match the separately entered start reference and source file.</small></label>
    <label>Exact end waypoint, if ambiguous<select name="end_waypoint_id"><option value="">Resolve by text reference and source file</option>@foreach($batch->sources->where('kind', 'gpx') as $source)@foreach($source->waypoints as $point)<option value="{{ $point->id }}" @selected((string) $value('end_waypoint_id') === (string) $point->id)>#{{ $point->id }} {{ $point->name }} | {{ $source->original_name }} v{{ $source->version }} | {{ $point->latitude }}, {{ $point->longitude }}{{ $point->recorded_at ? ' | '.$point->recorded_at->timezone('Asia/Karachi')->format('d M Y H:i:s').' PKT' : '' }}</option>@endforeach @endforeach</select><small>The exact point must match the separately entered end reference and source file.</small></label>
    <label>Start reference as written<input name="original_entry[start_reference]" value="{{ $value('original_entry.start_reference') }}" maxlength="200"></label>
    <label>End reference as written<input name="original_entry[end_reference]" value="{{ $value('original_entry.end_reference') }}" maxlength="200"></label>
    <fieldset class="mdb-span-all"><legend>Verified phase configuration</legend><div class="mdb-phase-checks">@foreach(['R','Y','B','N'] as $phase)<label><input type="checkbox" name="phases[]" value="{{ $phase }}" @checked(in_array($phase, (array) $value('phases', []), true)) data-copy-key="phase_{{ $phase }}">{{ $phase === 'N' ? 'Neutral' : $phase }}</label>@endforeach</div><small>Each selected phase and neutral requires its own conductor code. A missing configuration remains unresolved.</small></fieldset>
    <label class="mdb-span-all">Phase configuration as written<input name="original_entry[phases]" value="{{ $value('original_entry.phases') }}" maxlength="100"></label>
    @foreach(['R'=>'R phase conductor','Y'=>'Y phase conductor','B'=>'B phase conductor','N'=>'Neutral conductor'] as $phase=>$label)
    <label>{{ $label }} code<input name="conductors[{{ $phase }}]" value="{{ $value('conductors.'.$phase) }}" maxlength="200" data-copy-key="conductor_{{ $phase }}"></label>
    <label>{{ $label }} as written<input name="original_entry[conductor_{{ $phase }}]" value="{{ $value('original_entry.conductor_'.$phase) }}" maxlength="200"></label>
    @endforeach
    <label>Equipment type<input name="equipment_type" value="{{ $value('equipment_type') }}" maxlength="100" data-copy-key="equipment_type"></label>
    <label>Equipment type as written<input name="original_entry[equipment_type]" value="{{ $value('original_entry.equipment_type') }}" maxlength="200"></label>
    <label>Approved equipment library reference<input name="equipment_ref" value="{{ $value('equipment_ref') }}" maxlength="200" data-copy-key="equipment_ref"><small>Use an approved reference present in the target SynerGEE library.</small></label>
    <label>Pole class<input name="pole_class" value="{{ $value('pole_class') }}" maxlength="100" data-copy-key="pole_class"></label>
    <label>Pole class as written<input name="original_entry[pole_class]" value="{{ $value('original_entry.pole_class') }}" maxlength="200"></label>
    <label>Pole height<input name="pole_height" value="{{ $value('pole_height') }}" type="number" min="0" step="any" data-copy-key="pole_height"></label>
    <label>Pole height unit<select name="pole_height_unit" data-copy-key="pole_height_unit"><option value="">Not recorded</option>@foreach(['m'=>'metres','ft'=>'feet'] as $unit=>$label)<option value="{{ $unit }}" @selected($value('pole_height_unit') === $unit)>{{ $label }}</option>@endforeach</select></label>
    <label>Pole height and unit as written<input name="original_entry[pole_height]" value="{{ $value('original_entry.pole_height') }}" maxlength="200"></label>
    <label>Printed Int field as written<input name="original_entry[int]" value="{{ $value('original_entry.int') }}" maxlength="200"><small>Preserve the printed value; confirm its interpretation during review.</small></label>
    <label>Survey group as written<input name="original_entry[team_group]" value="{{ $value('original_entry.team_group') }}" maxlength="200"></label>
    <label>Observation date as written<input name="original_entry[date]" value="{{ $value('original_entry.date') }}" maxlength="200"></label>
</div>
<h3>Consumer counts printed on the form</h3><p class="mdb-note">Blank means unrecorded. Enter zero only when verified. Customer counts are kept separately from demand. The meanings of LC and Int require confirmation.</p>
<div class="mdb-consumers">@foreach(['rs','rl','sc','lc','si','li','pb','ag','st'] as $category)
    <div class="mdb-consumer"><strong>{{ strtoupper($category) }}</strong><div class="mdb-fields"><label>Verified count<input name="consumers[{{ $category }}][count]" value="{{ $consumerValue($category, 'count') }}" type="number" min="0" max="1000000" step="1"></label><label>As written<input name="consumers[{{ $category }}][original_value]" value="{{ $consumerValue($category, 'original_value') }}" maxlength="200"></label></div>
    <details><summary>Recorded demand and phase allocation</summary><div class="mdb-fields"><label>Measurement / approved method<input name="consumers[{{ $category }}][demand][method]" value="{{ $consumerValue($category, 'demand.method') }}" maxlength="500"></label><label>Evidence<input name="consumers[{{ $category }}][demand][evidence]" value="{{ $consumerValue($category, 'demand.evidence') }}" maxlength="2000"></label></div>@foreach(['R','Y','B'] as $phase)<details><summary>{{ $phase }} phase recorded demand</summary><div class="mdb-fields"><label>Allocated customers<input name="consumers[{{ $category }}][demand][phase_values][{{ $phase }}][customers]" value="{{ $consumerValue($category, 'demand.phase_values.'.$phase.'.customers') }}" type="number" min="0" step="1"></label>@foreach(['kw'=>'kW','kvar'=>'kvar','kva'=>'kVA'] as $key=>$label)<label>{{ $label }}<input name="consumers[{{ $category }}][demand][phase_values][{{ $phase }}][{{ $key }}]" value="{{ $consumerValue($category, 'demand.phase_values.'.$phase.'.'.$key) }}" type="number" @if($key !== 'kvar') min="0" @endif step="any"></label>@endforeach</div></details>@endforeach<small>A verifier must approve the recorded demand; no phase allocation or power factor is inferred.</small></details></div>
    @endforeach
</div>
<h3>Source and length provenance</h3><div class="mdb-fields">
    <label>Source PDF<select name="source_pdf_id" required><option value="">Choose PDF</option>@foreach($batch->sources->where('kind', 'pdf') as $source)<option value="{{ $source->id }}" @selected((string) $value('source_pdf_id') === (string) $source->id)>{{ $source->original_name }} v{{ $source->version }}</option>@endforeach</select></label>
    <label>PDF page<input name="source_page" value="{{ $value('source_page') }}" type="number" min="1" max="10000" required></label>
    <label>Survey row reference<input name="source_row" value="{{ $value('source_row') }}" maxlength="60" required placeholder="Example: S row 1 / E row 2"></label>
    <label>Approved measured length (m)<input name="measured_length_m" value="{{ $value('measured_length_m') }}" type="number" min="0.001" step="any"><small>Requires verifier approval. Endpoint distance remains an estimate.</small></label>
    <label class="mdb-span-all">Measured length reason / evidence<textarea name="measured_length_reason" maxlength="4000" rows="2">{{ $value('measured_length_reason') }}</textarea></label>
    <label class="mdb-span-all">Intermediate WGS84 geometry (optional JSON)<textarea name="geometry_json" rows="2" class="mdb-json" placeholder='[{"latitude": 30.0, "longitude": 71.0}]'>{{ data_get($submitted, 'geometry_json', is_array($value('geometry')) ? json_encode($value('geometry'), JSON_UNESCAPED_SLASHES) : $value('geometry')) }}</textarea><small>Provide recorded intermediate points in traversal order. Endpoints are never connected by sorting waypoint names.</small></label>
    <label class="mdb-span-all">Row remarks as written<textarea name="original_entry[remarks]" maxlength="4000" rows="2">{{ $value('original_entry.remarks') }}</textarea></label>
    <label class="mdb-check mdb-span-all"><input name="original_entry[manually_verified]" type="checkbox" value="1" @checked($value('original_entry.manually_verified', false)) required>I checked this section, its endpoint pair and consumer counts against the original PDF row.</label>
</div>
<div class="mdb-form-actions"><button class="btn btn-primary">{{ $section ? 'Save section and consumer observations' : 'Add verified section entry' }}</button><small>Saving records a new revision; final approval requires network validation.</small></div>
