@extends('layouts.app')
@section('title',$transformer->transformer_code)
@section('content')
<div class="page-head"><div><span class="eyebrow">Transformer GIS record</span><h1>{{ $transformer->transformer_code }}</h1><p>{{ $transformer->feeder->feeder_code }} · {{ $transformer->feeder->feeder_name }}</p></div><div class="actions"><a class="btn btn-light" href="{{ route('transformers.index', request()->only(['q','feeder_id','capacity'])) }}">Back to list</a><a class="btn btn-primary" target="_blank" rel="noopener" href="{{ $transformer->map_url }}">Open in map</a></div></div>

<div class="grid transformer-detail-grid">
    <section class="card"><div class="section-title"><h2>Identity &amp; location</h2><span class="status">{{ $transformer->equipment_status ?: 'Status not stated' }}</span></div><dl class="detail-list"><div><dt>Linked Excel feeder</dt><dd>{{ $transformer->feeder->feeder_code }} — {{ $transformer->feeder->feeder_name }}</dd></div><div><dt>KMZ source feeder</dt><dd>{{ $transformer->source_feeder_name }}</dd></div><div><dt>KMZ substation</dt><dd>{{ $transformer->source_substation_name ?: '—' }}</dd></div><div><dt>GPS waypoint</dt><dd>{{ $transformer->gps_waypoint_number ?: '—' }}</dd></div><div><dt>Equipment location</dt><dd>{{ $transformer->equipment_location ?: '—' }}</dd></div><div><dt>Coordinates</dt><dd>{{ $transformer->latitude }}, {{ $transformer->longitude }}</dd></div></dl></section>
    <section class="card"><div class="section-title"><h2>Transformer details</h2><strong>{{ number_format((float) $transformer->capacity_kva, 0) }} kVA</strong></div><dl class="detail-list"><div><dt>Make</dt><dd>{{ $transformer->equipment_make ?: '—' }}</dd></div><div><dt>Name</dt><dd>{{ $transformer->equipment_name ?: '—' }}</dd></div><div><dt>Phase</dt><dd>{{ $transformer->equipment_phase ?: '—' }}</dd></div><div><dt>Use</dt><dd>{{ $transformer->equipment_use ?: '—' }}</dd></div><div><dt>Mounting</dt><dd>{{ $transformer->equipment_mounting ?: '—' }}</dd></div><div><dt>Line voltage</dt><dd>{{ $transformer->line_voltage ?: '—' }}</dd></div></dl></section>
    <section class="card"><div class="section-title"><h2>Pole &amp; conductor</h2></div><dl class="detail-list"><div><dt>Pole number</dt><dd>{{ $transformer->pole_number ?: '—' }}</dd></div><div><dt>Pole type / height</dt><dd>{{ collect([$transformer->pole_type, $transformer->pole_height ? $transformer->pole_height.' ft' : null])->filter()->join(' · ') ?: '—' }}</dd></div><div><dt>Pole phase / use</dt><dd>{{ collect([$transformer->pole_phase, $transformer->pole_use])->filter()->join(' · ') ?: '—' }}</dd></div><div><dt>R / Y / B conductors</dt><dd>{{ collect([$transformer->conductor_phase_r, $transformer->conductor_phase_y, $transformer->conductor_phase_b])->map(fn($v) => $v ?: '—')->join(' / ') }}</dd></div><div><dt>Neutral</dt><dd>{{ $transformer->conductor_neutral ?: '—' }}</dd></div><div><dt>End type</dt><dd>{{ $transformer->end_type ?: '—' }}</dd></div></dl></section>
    <section class="card"><div class="section-title"><h2>Recorded consumers</h2></div><dl class="detail-list detail-list-numbers"><div><dt>Residential single-phase</dt><dd>{{ number_format($transformer->residential_single) }}</dd></div><div><dt>Residential three-phase</dt><dd>{{ number_format($transformer->residential_three) }}</dd></div><div><dt>Residential total</dt><dd>{{ number_format($transformer->residential_total) }}</dd></div><div><dt>Small / large commercial</dt><dd>{{ number_format($transformer->small_commercial) }} / {{ number_format($transformer->large_commercial) }}</dd></div><div><dt>Small / large industries</dt><dd>{{ number_format($transformer->small_industries) }} / {{ number_format($transformer->large_industries) }}</dd></div><div><dt>Public / agricultural / street light</dt><dd>{{ number_format($transformer->public_use) }} / {{ number_format($transformer->agricultural) }} / {{ number_format($transformer->street_lights) }}</dd></div></dl></section>
</div>

<section class="card"><div class="section-title"><h2>Source &amp; remarks</h2></div><dl class="detail-list"><div><dt>Remarks</dt><dd>{{ $transformer->remarks ?: '—' }}</dd></div><div><dt>Source picture path</dt><dd>{{ $transformer->source_picture_path ?: '—' }}</dd></div><div><dt>Last KMZ import</dt><dd>{{ $transformer->kmzImport?->imported_at?->format('d M Y, h:i A') ?: '—' }}@if($transformer->kmzImport?->importer) · {{ $transformer->kmzImport->importer->name }}@endif</dd></div></dl></section>
@endsection
