@extends('layouts.app')
@section('title',$report['title'])
@section('content')
<div class="page-head"><div><h1>{{ $report['title'] }}</h1><p>Generated {{ now()->format('d M Y h:i A') }} · {{ count($report['rows']) }} rows.</p></div><div class="actions"><a class="btn btn-light" href="{{ route('reports.csv',request()->query()) }}">Export CSV / Excel</a><button class="btn btn-primary" onclick="window.print()">Print / Save PDF</button></div></div>
<form class="card no-print" method="GET">
<div class="form-grid">
<div class="field"><label>Report</label><select name="report">@foreach($reportTypes as $key=>$label)<option value="{{ $key }}" @selected($type===$key)>{{ $label }}</option>@endforeach</select></div>
<div class="field"><label>Date from</label><input type="date" name="from" value="{{ $filters['from'] }}"></div><div class="field"><label>Date to</label><input type="date" name="to" value="{{ $filters['to'] }}"></div>
<div class="field"><label>Circle</label><select name="circle_id"><option value="">All circles</option>@foreach($circles as $option)<option value="{{ $option->id }}" @selected(($filters['circle_id']??null)==$option->id)>{{ $option->name }}</option>@endforeach</select></div>
<div class="field"><label>Division</label><select name="division_id"><option value="">All divisions</option>@foreach($divisions as $option)<option value="{{ $option->id }}" @selected(($filters['division_id']??null)==$option->id)>{{ $option->name }}</option>@endforeach</select></div>
<div class="field"><label>Grid Station</label><select name="grid_station_id"><option value="">All grid stations</option>@foreach($grids as $option)<option value="{{ $option->id }}" @selected(($filters['grid_station_id']??null)==$option->id)>{{ $option->name }}</option>@endforeach</select></div>
<div class="field"><label>Feeder</label><select name="feeder_id"><option value="">All feeders</option>@foreach($feeders as $option)<option value="{{ $option->id }}" @selected(($filters['feeder_id']??null)==$option->id)>{{ $option->feeder_code }} · {{ $option->feeder_name }}</option>@endforeach</select></div>
<div class="field"><label>Survey Team</label><select name="survey_team_id"><option value="">All survey teams</option>@foreach($surveyTeams as $option)<option value="{{ $option->id }}" @selected(($filters['survey_team_id']??null)==$option->id)>{{ $option->name }}</option>@endforeach</select></div>
<div class="field"><label>Processing Organization</label><select name="organization_id"><option value="">All organizations</option>@foreach($organizations as $option)<option value="{{ $option->id }}" @selected(($filters['organization_id']??null)==$option->id)>{{ $option->name }}</option>@endforeach</select></div>
<div class="field"><label>Feeder Status</label><select name="progress_status"><option value="">All feeder statuses</option>@foreach(['NOT STARTED','SURVEY RUNNING','VERIFICATION PENDING','MDB CREATION RUNNING','MDB PROCESSING RUNNING','COMPLETED'] as $status)<option value="{{ $status }}" @selected(($filters['progress_status']??null)===$status)>{{ $status }}</option>@endforeach</select></div>
<div class="field"><label>Assignment Status</label><select name="assignment_status"><option value="">All assignment statuses</option>@foreach(['active','completed','cancelled'] as $status)<option value="{{ $status }}" @selected(($filters['assignment_status']??null)===$status)>{{ strtoupper($status) }}</option>@endforeach</select></div>
</div><div class="form-footer"><a href="{{ route('reports.index') }}" class="btn btn-light">Clear</a><button class="btn btn-primary">Generate report</button></div></form>
<div class="card table-wrap"><table class="table"><thead><tr>@foreach($report['headers'] as $header)<th>{{ $header }}</th>@endforeach</tr></thead><tbody>@forelse($report['rows'] as $row)<tr>@foreach((array)$row as $value)<td>{{ $value }}</td>@endforeach</tr>@empty<tr><td colspan="{{ count($report['headers']) }}" class="empty">No records match the selected report and filters.</td></tr>@endforelse</tbody></table></div>
@endsection
