@extends('layouts.app')
@section('title', 'Survey batch #'.$batch->id)
@section('content')
@php
    $pdfs = $batch->sources->where('kind', 'pdf');
    $gpxs = $batch->sources->where('kind', 'gpx');
    $selectedTransformer = $batch->transformers->firstWhere('id', (int) request('transformer_id')) ?? $batch->transformers->first();
    $firstPdf = $pdfs->first();
    $issues = $validation['errors'] ?? [];
    $warnings = $validation['warnings'] ?? [];
@endphp
<div class="mdb-workflow">
    <div class="page-head"><div><span class="eyebrow">{{ $batch->project?->name }} / {{ $batch->feeder?->feeder_code }}</span><h1>Survey batch #{{ $batch->id }}</h1><p>{{ $batch->feeder?->feeder_name }} &middot; {{ $batch->surveyTeam?->name }} &middot; {{ $batch->survey_date?->format('d M Y') }}</p></div><a class="btn btn-light" href="{{ route('mdb-workflow.index') }}">All batches</a></div>
    <div class="mdb-summary"><span class="status mdb-status-{{ $batch->status }}">{{ str($batch->status)->replace('_', ' ')->title() }}</span><p><strong>Data revision {{ $batch->revision }}</strong> &middot; {{ $batch->transformers->count() }} transformer records &middot; {{ $batch->sources->count() }} source versions. @if($batch->approved_revision_id)Approval is bound to revision #{{ $batch->approvedRevision?->number }}.@else This revision has no final approval.@endif</p></div>
    <nav class="mdb-tabs" aria-label="Batch sections"><a href="{{ route('mdb-workflow.show', [$batch, 'transformer_id'=>$selectedTransformer?->id]) }}">Simple operator entry</a><a href="{{ route('mdb-workflow.review', [$batch, 'transformer_id'=>$selectedTransformer?->id]) }}">Review &amp; save</a><a href="#sources">Source files</a><a href="#entry">Engineering entry</a><a href="#validation">Validation</a><a href="#review">Verification</a><a href="#exports">MDB exports and analysis</a></nav>
    <section class="card" id="sources"><h2>Original source files and versions</h2>
        <div class="table-wrap"><table class="table mdb-table"><thead><tr><th>Source</th><th>Version / uploaded</th><th>Processing</th><th>Integrity</th><th></th></tr></thead><tbody>
        @forelse($batch->sources as $source)<tr><td><strong>{{ $source->original_name }}</strong><small>{{ strtoupper($source->kind) }} &middot; {{ number_format($source->bytes / 1024, 1) }} KB</small>@if($source->parent_source_id)<small>Supersedes source #{{ $source->parent_source_id }}; original retained.</small>@endif</td><td>v{{ $source->version }}<small>{{ $source->created_at?->timezone('Asia/Karachi')->format('d M Y H:i') }} PKT</small></td><td><span class="status mdb-status-{{ $source->status }}">{{ str($source->status ?? 'uploaded')->replace('_', ' ')->title() }}</span>@if($source->kind === 'gpx')<small>{{ $source->waypoints->count() }} waypoint records</small>@endif @if(data_get($source->metadata, 'error'))<small class="mdb-inline-error">{{ data_get($source->metadata, 'error') }}</small>@endif</td><td><small class="mdb-source-hash">SHA-256 {{ $source->sha256 }}</small></td><td><a class="btn btn-sm btn-light" href="{{ route('mdb-workflow.source', [$batch, $source]) }}" @if($source->kind === 'pdf') target="_blank" rel="noopener" @endif>{{ $source->kind === 'pdf' ? 'View original PDF' : 'Download original GPX' }}</a>@if($source->status === 'failed')@can('mdb-workflow.upload')<form method="POST" action="{{ route('mdb-workflow.sources.retry', [$batch, $source]) }}">@csrf<input type="hidden" name="revision" value="{{ $batch->revision }}"><button class="btn btn-sm btn-light">Retry source processing</button></form>@endcan @endif</td></tr>
        @empty<tr><td colspan="5" class="empty">Upload the survey PDFs and matching GPX files.</td></tr>@endforelse
        </tbody></table></div>
        @can('mdb-workflow.upload')
        <details @if($batch->sources->isEmpty()) open @endif><summary>Upload a source file or new version</summary><form method="POST" enctype="multipart/form-data" action="{{ route('mdb-workflow.sources.store', $batch) }}">@csrf<input type="hidden" name="revision" value="{{ $batch->revision }}">
            <div class="mdb-fields"><label>Original PDF or GPX<input name="file" type="file" accept=".pdf,.gpx,application/pdf,application/gpx+xml" @if(!config('services.google_drive.enabled')) required @endif><small>PDF up to {{ config('mdb_workflow.max_pdf_mb', 100) }} MB; GPX up to 10 MB. Originals remain private and are processed by the background queue.</small></label><label>Version of existing source<select name="parent_source_id"><option value="">New independent source</option>@foreach($batch->sources as $source)<option value="{{ $source->id }}">{{ $source->original_name }} v{{ $source->version }}</option>@endforeach</select><small>Choose an existing file only when this upload is its replacement version.</small></label>@if(config('services.google_drive.enabled'))<label class="mdb-span-all">Import an authorized Google Drive file ID<input name="drive_file_id" maxlength="200"><small>Provide a retrievable file from your connected Drive account. The system preserves an authorized private copy for processing. <a href="{{ route('google-drive.index') }}">Manage Drive connection</a></small></label>@endif</div><div class="mdb-form-actions"><button class="btn btn-primary">Upload and preserve source</button></div>
        </form></details>
        @endcan
        @if($gpxs->isNotEmpty())<details><summary>Inspect extracted GPX waypoints</summary><p class="mdb-note">Names are text and scoped to each GPX source. Original times are stored in UTC and displayed in Pakistan time. Coordinate corrections preserve the original observation.</p>
        @foreach($gpxs as $source)<h3>{{ $source->original_name }} v{{ $source->version }}</h3><div class="mdb-waypoints"><table class="table"><thead><tr><th>Name</th><th>Original WGS84 position</th><th>Elevation / time</th><th>Description / correction</th></tr></thead><tbody>@foreach($source->waypoints as $waypoint)
        <tr><td class="mdb-code">{{ $waypoint->name }}</td><td>{{ $waypoint->latitude }}, {{ $waypoint->longitude }}</td><td>{{ $waypoint->elevation !== null ? $waypoint->elevation.' m' : 'Not recorded' }}<small>{{ $waypoint->recorded_at?->timezone('Asia/Karachi')->format('d M Y H:i:s') ?? 'No timestamp' }}{{ $waypoint->recorded_at ? ' PKT' : '' }}</small></td><td>{{ $waypoint->description }}@if($waypoint->correction)<small>Approved correction: {{ data_get($waypoint->correction, 'latitude') }}, {{ data_get($waypoint->correction, 'longitude') }}<br>{{ data_get($waypoint->correction, 'reason') }}</small>@endif
        @can('mdb-workflow.verify')<details><summary>Approve documented correction</summary><form method="POST" action="{{ route('mdb-workflow.waypoints.corrections.store', [$batch, $waypoint]) }}">@csrf<input type="hidden" name="revision" value="{{ $batch->revision }}"><div class="mdb-fields"><label>Corrected latitude<input name="latitude" type="number" min="-90" max="90" step="any" required></label><label>Corrected longitude<input name="longitude" type="number" min="-180" max="180" step="any" required></label><label class="mdb-span-all">Reason<textarea name="reason" required minlength="5" maxlength="4000" rows="2"></textarea></label><label class="mdb-span-all">Evidence<input name="evidence" required maxlength="2000"></label></div><button class="btn btn-sm btn-primary">Record verifier-approved correction</button></form></details>@endcan
        </td></tr>@endforeach</tbody></table></div>@endforeach</details>@endif
    </section>
    <section class="card" id="entry"><div class="page-head"><div><h2>Transformer networks</h2><p>Associate each PDF page explicitly, then enter the surveyed start and end pairs. Repeated endpoints form branches.</p></div></div>
        <div class="actions">@foreach($batch->transformers as $transformer)<a class="btn {{ $selectedTransformer?->id === $transformer->id ? 'btn-primary' : 'btn-light' }}" href="{{ route('mdb-workflow.show', [$batch, 'transformer_id'=>$transformer->id]) }}#entry">{{ $transformer->code }} <small>{{ $transformer->sections->count() }} sections</small></a>@endforeach</div>
        @can('mdb-workflow.edit')<details @if(!$selectedTransformer) open @endif><summary>Add transformer network</summary><form method="POST" action="{{ route('mdb-workflow.transformers.store', $batch) }}">@csrf @include('mdb-workflow.partials.transformer-form', ['transformer'=>null, 'formKey'=>'transformer-new'])</form></details>@endcan
        @if(!$selectedTransformer)<p class="mdb-note">Create the transformer header to begin section data entry.</p>@endif
    </section>
    @if($selectedTransformer)
    <div class="mdb-editor">
        <aside class="mdb-reference" aria-label="Survey PDF reference"><section class="card"><h2>Survey PDF reference</h2>
            @if($firstPdf)<div class="mdb-viewer-controls"><label>PDF source<select id="mdb-pdf-source">@foreach($pdfs as $source)<option value="{{ $source->id }}" data-url="{{ route('mdb-workflow.source', [$batch, $source]) }}">{{ $source->original_name }} v{{ $source->version }}</option>@endforeach</select></label><label>Page<input id="mdb-pdf-page" type="number" min="1" max="10000" value="1"></label><div class="actions"><button class="btn btn-sm btn-light" id="mdb-pdf-go" type="button">Go to page</button><a class="btn btn-sm btn-light" id="mdb-pdf-open" href="{{ route('mdb-workflow.source', [$batch, $firstPdf]) }}" target="_blank" rel="noopener">Open PDF separately</a></div></div><iframe id="mdb-pdf-viewer" src="{{ route('mdb-workflow.source', [$batch, $firstPdf]) }}#page=1" title="Original survey PDF beside data entry"></iframe><small>Use the separate PDF window if your browser cannot display the embedded viewer.</small>@else<p class="empty">Upload a PDF source to view it beside the survey form.</p>@endif
        </section></aside>
        <div>
            <section class="card" id="transformer-{{ $selectedTransformer->id }}"><h2>{{ $selectedTransformer->code }} header</h2>
                @can('mdb-workflow.edit')<details @if(old('form_key') === 'transformer-'.$selectedTransformer->id) open @endif><summary>Edit and verify transformer header</summary><form method="POST" action="{{ route('mdb-workflow.transformers.update', [$batch, $selectedTransformer]) }}">@csrf @method('PUT') @include('mdb-workflow.partials.transformer-form', ['transformer'=>$selectedTransformer, 'formKey'=>'transformer-'.$selectedTransformer->id])</form></details>@endcan
                <dl class="detail-list"><div><dt>Capacity</dt><dd>{{ $selectedTransformer->capacity_kva !== null ? $selectedTransformer->capacity_kva.' kVA' : 'Unresolved' }}</dd></div><div><dt>Transformer waypoint</dt><dd>{{ $selectedTransformer->sourceWaypoint?->name ?? 'Unresolved' }}</dd></div><div><dt>Make</dt><dd>{{ data_get($selectedTransformer->header, 'make') ?: 'Not recorded' }}</dd></div><div><dt>Location</dt><dd>{{ data_get($selectedTransformer->header, 'location') ?: 'Not recorded' }}</dd></div></dl>
                <details><summary>Review transformer header and original transcription</summary><dl class="detail-list">@foreach(['feeder_identifier'=>'Feeder identifier','feeder_name'=>'Feeder name','substation_identifier'=>'Substation identifier','substation_name'=>'Substation name','mounting'=>'Mounting','survey_date'=>'Survey date','team_group'=>'Survey group','inspector'=>'Inspector','remarks'=>'Remarks'] as $key=>$label)<div><dt>{{ $label }}</dt><dd>{{ data_get($selectedTransformer->header, $key) ?: 'Unrecorded' }}<small>As written: {{ data_get($selectedTransformer->original_header, $key) ?: 'Unrecorded' }}</small></dd></div>@endforeach</dl><p class="mdb-note">Manual header verification: {{ data_get($selectedTransformer->header, 'manually_verified') ? 'confirmed' : 'pending' }}.</p></details>
                <h3>Associated PDF pages</h3>
                @forelse(data_get($selectedTransformer->header, 'pages', []) as $pageIndex=>$page)
                    <div class="mdb-page-association"><p class="mdb-note"><a href="#mdb-pdf-viewer" data-mdb-pdf-source="{{ $page['source_pdf_id'] ?? $page['source_id'] ?? '' }}" data-mdb-pdf-page="{{ $page['page'] ?? $page['source_page'] ?? 1 }}">Source #{{ $page['source_pdf_id'] ?? $page['source_id'] ?? '?' }}, page {{ $page['page'] ?? $page['source_page'] ?? '?' }}</a> &middot; {{ $page['role'] ?? 'Continuation' }}</p>
                        @can('mdb-workflow.edit')<details><summary>Remove incorrect page association</summary><form method="POST" action="{{ route('mdb-workflow.pages.destroy', [$batch, $selectedTransformer, $pageIndex]) }}" data-mdb-confirm="Remove this PDF page's association with this transformer? The original PDF and audit history remain preserved, and this change requires renewed header verification.">@csrf @method('DELETE')<input type="hidden" name="revision" value="{{ $batch->revision }}"><div class="mdb-fields"><label class="mdb-span-all">Reason<input name="reason" required minlength="5" maxlength="4000"></label><label class="mdb-check mdb-span-all"><input type="checkbox" name="confirmed" value="1" required>I confirm this PDF page association is incorrect.</label></div><div class="mdb-form-actions"><button class="btn btn-sm btn-danger">Remove association and retain source</button></div></form></details>@endcan
                    </div>
                @empty<p class="mdb-note">No explicit PDF page associations yet.</p>@endforelse
                @can('mdb-workflow.edit')<form method="POST" action="{{ route('mdb-workflow.pages.store', [$batch, $selectedTransformer]) }}">@csrf<input type="hidden" name="revision" value="{{ $batch->revision }}"><div class="mdb-fields"><label>PDF source<select name="source_pdf_id" required><option value="">Choose PDF</option>@foreach($pdfs as $source)<option value="{{ $source->id }}">{{ $source->original_name }} v{{ $source->version }}</option>@endforeach</select></label><label>PDF page<input name="page" type="number" min="1" max="10000" required></label><label class="mdb-span-all">Association<select name="role"><option value="header">Transformer header page</option><option value="continuation">Continuation of this transformer</option><option value="pv">PV observations for this transformer</option></select></label><label class="mdb-check mdb-span-all"><input name="confirmed" type="checkbox" value="1" required>I checked that this page belongs to {{ $selectedTransformer->code }} and shares this transformer header.</label></div><div class="mdb-form-actions"><button class="btn btn-light">Associate page explicitly</button></div></form>@endcan
            </section>
            <section class="card"><h2>Survey sections</h2><p class="mdb-note">Each section records its own endpoint pair and PDF row. Original transcription and verified values remain separate.</p>
                @forelse($selectedTransformer->sections as $section)<article id="section-{{ $section->id }}" class="row-card"><div class="row-card-head"><strong>{{ $section->start_reference }} &rarr; {{ $section->end_reference }}</strong><a href="#mdb-pdf-viewer" data-mdb-pdf-source="{{ $section->source_pdf_id }}" data-mdb-pdf-page="{{ $section->source_page }}">Page {{ $section->source_page }}, row {{ $section->source_row }}</a></div><p class="mdb-note">Phases {{ implode('/', $section->phases ?? []) ?: 'unresolved' }} &middot; Equipment {{ $section->equipment_ref ?: 'unresolved' }} @if($section->measured_length_m !== null)&middot; Measured {{ $section->measured_length_m }} m ({{ $section->length_approved_by ? 'verifier approved' : 'awaiting approval' }})@endif</p>
                    <details><summary>Review verified survey values and consumer observations</summary><dl class="detail-list"><div><dt>Endpoint source files</dt><dd>Start #{{ $section->start_source_file_id ?? '?' }} / End #{{ $section->end_source_file_id ?? '?' }}</dd></div><div><dt>Equipment type</dt><dd>{{ $section->equipment_type ?: 'Unresolved' }}</dd></div>@foreach(['R','Y','B','N'] as $phase)<div><dt>{{ $phase === 'N' ? 'Neutral' : $phase.' phase' }} conductor</dt><dd>{{ data_get($section->conductors, $phase) ?: 'Unrecorded' }}<small>As written: {{ data_get($section->original_entry, 'conductor_'.$phase) ?: 'Unrecorded' }}</small></dd></div>@endforeach<div><dt>Pole</dt><dd>{{ $section->pole_class ?: 'Unrecorded' }} / {{ $section->pole_height ?? 'Unrecorded' }} {{ $section->pole_height_unit }}<small>As written: {{ data_get($section->original_entry, 'pole_class') }} {{ data_get($section->original_entry, 'pole_height') }}</small></dd></div><div><dt>Manual source verification</dt><dd>{{ data_get($section->original_entry, 'manually_verified') ? 'Confirmed' : 'Pending' }}</dd></div></dl>
                        <div class="table-wrap"><table class="table mdb-review-table"><thead><tr><th>Printed category</th><th>Verified count / as written</th><th>Recorded demand and phase allocation</th></tr></thead><tbody>@forelse($section->consumers as $consumer)<tr><td>{{ strtoupper($consumer->category) }}</td><td>{{ $consumer->count ?? 'Unrecorded' }}<small>As written: {{ $consumer->original_value ?? 'Unrecorded' }}</small></td><td>@if($consumer->demand)<strong>{{ data_get($consumer->demand, 'method') }}</strong><small>Evidence: {{ data_get($consumer->demand, 'evidence') }}</small>@foreach(data_get($consumer->demand, 'phase_values', []) as $phase=>$demand)<small>{{ $phase }}: {{ $demand['customers'] ?? '?' }} customers; {{ $demand['kw'] ?? '?' }} kW; {{ $demand['kvar'] ?? '?' }} kvar; {{ $demand['kva'] ?? '?' }} kVA.</small>@endforeach<small>{{ data_get($consumer->demand, 'approved_by') ? 'Verifier approved' : 'Awaiting demand approval' }}</small>@else Unrecorded demand @endif</td></tr>@empty<tr><td colspan="3">Consumer observations not entered.</td></tr>@endforelse</tbody></table></div>
                    </details>
                    @can('mdb-workflow.edit')<details @if(old('form_key') === 'section-'.$section->id) open @endif><summary>Edit this section</summary><form method="POST" action="{{ route('mdb-workflow.sections.update', [$batch, $selectedTransformer, $section]) }}" data-mdb-section-form>@csrf @method('PUT') @include('mdb-workflow.partials.section-form', ['section'=>$section, 'formKey'=>'section-'.$section->id])</form></details>@endcan
                    @can('mdb-workflow.verify')
                    @if($section->measured_length_m !== null && !$section->length_approved_by)<form method="POST" action="{{ route('mdb-workflow.sections.length.approve', [$batch, $selectedTransformer, $section]) }}">@csrf<input type="hidden" name="revision" value="{{ $batch->revision }}"><div class="mdb-fields"><label class="mdb-span-all">Measured length approval reason<input name="reason" required minlength="5" maxlength="2000" placeholder="Confirm measurement evidence and its suitability"></label></div><div class="mdb-form-actions"><button class="btn btn-sm btn-success">Approve measured length</button></div></form>@endif
                    @foreach($section->consumers as $consumer)@if($consumer->demand && !data_get($consumer->demand, 'approved_by'))<form method="POST" action="{{ route('mdb-workflow.consumers.approve', [$batch, $selectedTransformer, $section, $consumer]) }}">@csrf<input type="hidden" name="revision" value="{{ $batch->revision }}"><div class="mdb-fields"><label class="mdb-span-all">{{ strtoupper($consumer->category) }} demand review evidence<input name="reason" required minlength="5" maxlength="2000"></label></div><div class="mdb-form-actions"><button class="btn btn-sm btn-success">Approve {{ strtoupper($consumer->category) }} demand allocation</button></div></form>@endif @endforeach
                    @endcan
                    <details><summary>Retained original entry</summary><pre class="mdb-code">{{ json_encode($section->original_entry, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES) }}</pre></details>
                    @can('mdb-workflow.edit')<details><summary>Remove an incorrect section</summary><p class="mdb-note">The prior revision and audit history retain this observation. Its PV records remain associated with the transformer until reassigned.</p><form method="POST" action="{{ route('mdb-workflow.sections.destroy', [$batch, $selectedTransformer, $section]) }}" data-mdb-confirm="Remove this section from the current network? This creates a new revision, invalidates approval and supersedes previous MDB outputs.">@csrf @method('DELETE')<input type="hidden" name="revision" value="{{ $batch->revision }}"><div class="mdb-fields"><label class="mdb-span-all">Reason for removing this section<textarea name="reason" required minlength="5" maxlength="4000" rows="2"></textarea></label><label class="mdb-check mdb-span-all"><input name="confirmed" type="checkbox" value="1" required>I checked the source survey and confirm this section should be removed from the current network.</label></div><div class="mdb-form-actions"><button class="btn btn-danger">Remove section and retain audit history</button></div></form></details>@endcan
                </article>@empty<p class="empty">No sections entered for this transformer.</p>@endforelse
                @can('mdb-workflow.edit')<details @if(old('form_key') === 'section-new') open @endif><summary>Add surveyed section</summary>
                    @if($selectedTransformer->sections->isNotEmpty())<div class="mdb-copy-tools"><label>Copy repeated verified values from<select id="mdb-copy-section"><option value="">Choose existing section</option>@foreach($selectedTransformer->sections as $section)<option value="{{ $section->id }}">{{ $section->start_reference }} &rarr; {{ $section->end_reference }} | page {{ $section->source_page }} row {{ $section->source_row }}</option>@endforeach</select></label><button id="mdb-copy-confirm" class="btn btn-sm btn-light" type="button">Review and confirm ditto copy</button><small class="mdb-span-all">Copies phase, conductor and equipment values only after confirmation. Verify the new row and record its own endpoints and source.</small></div>@endif
                    <form method="POST" action="{{ route('mdb-workflow.sections.store', [$batch, $selectedTransformer]) }}" id="mdb-new-section-form" data-mdb-section-form>@csrf @include('mdb-workflow.partials.section-form', ['section'=>null, 'formKey'=>'section-new'])<input type="hidden" name="original_entry[ditto_copied_from_section_id]" id="mdb-ditto-source"><input type="hidden" name="original_entry[ditto_copy_confirmed]" id="mdb-ditto-confirmed"></form>
                </details>@endcan
            </section>
            <section class="card"><h2>PV / net metering observations</h2><div class="table-wrap"><table class="table mdb-table"><thead><tr><th>Consumer reference</th><th>Installed capacity (kW)</th><th>Section / source</th><th>Remarks</th></tr></thead><tbody>@forelse($selectedTransformer->pvRecords as $pv)<tr><td>{{ $pv->reference }}<small>As written: {{ data_get($pv->original_entry, 'reference') ?: 'Unrecorded' }}</small></td><td>{{ $pv->installed_capacity_kw ?? 'Unrecorded' }}<small>As written: {{ data_get($pv->original_entry, 'installed_capacity') ?: 'Unrecorded' }}</small></td><td>{{ $pv->section_id ? '#'.$pv->section_id : 'Transformer level' }}@if(data_get($pv->original_entry, 'source_page'))<small><a href="#mdb-pdf-viewer" data-mdb-pdf-source="{{ data_get($pv->original_entry, 'source_pdf_id') }}" data-mdb-pdf-page="{{ data_get($pv->original_entry, 'source_page') }}">PDF page {{ data_get($pv->original_entry, 'source_page') }}, row {{ data_get($pv->original_entry, 'source_row') }}</a></small>@endif</td><td>{{ $pv->remarks }}<small>As written: {{ data_get($pv->original_entry, 'remarks') ?: 'Unrecorded' }}</small></td></tr>@empty<tr><td colspan="4" class="empty">No PV observations entered.</td></tr>@endforelse</tbody></table></div>
                @can('mdb-workflow.edit')@foreach($selectedTransformer->pvRecords as $pv)<details @if(old('form_key') === 'pv-'.$pv->id) open @endif><summary>Correct PV observation {{ $pv->reference }}</summary><form method="POST" action="{{ route('mdb-workflow.pv.update', [$batch, $selectedTransformer, $pv]) }}">@csrf @method('PUT') @include('mdb-workflow.partials.pv-form', ['formKey'=>'pv-'.$pv->id])</form></details>@endforeach @endcan
                @can('mdb-workflow.edit')<details @if(old('form_key') === 'pv-new') open @endif><summary>Add PV observation</summary><form method="POST" action="{{ route('mdb-workflow.pv.store', [$batch, $selectedTransformer]) }}">@csrf @include('mdb-workflow.partials.pv-form', ['pv'=>null, 'formKey'=>'pv-new'])</form></details>@endcan
            </section>
        </div>
    </div>
    @endif
    <section class="card" id="validation"><h2>Current revision validation</h2><p class="mdb-note">Validation uses the surveyed endpoint pairs. Engineering warnings remain visible for review. Unresolved critical data blocks approval and final MDB export.</p>
        @if(!$issues)<div class="alert alert-success">No critical application validation errors in the current revision.</div>@else<ul class="mdb-issue-list">@foreach($issues as $issue)<li><strong>{{ $issue['code'] ?? 'Validation' }}</strong> &middot; {{ $issue['message'] ?? (is_string($issue) ? $issue : 'Unresolved value') }} @if(isset($issue['source_page']))<br><a href="#mdb-pdf-viewer" data-mdb-pdf-source="{{ $issue['source_pdf_id'] ?? '' }}" data-mdb-pdf-page="{{ $issue['source_page'] }}">PDF page {{ $issue['source_page'] }}, row {{ $issue['source_row'] ?? '?' }}</a>@endif @if(isset($issue['section_id']))<br><a href="{{ route('mdb-workflow.show', [$batch, 'transformer_id'=>$issue['transformer_id'] ?? $selectedTransformer?->id]) }}#section-{{ $issue['section_id'] }}">Open affected survey section</a>@endif</li>@endforeach</ul>@endif
        @if($warnings)<h3>Engineering review flags</h3><ul class="mdb-issue-list mdb-warnings">@foreach($warnings as $issue)<li>{{ $issue['message'] ?? (is_string($issue) ? $issue : 'Review required') }} @if(isset($issue['source_page']))<br>Page {{ $issue['source_page'] }}, row {{ $issue['source_row'] ?? '?' }}@endif</li>@endforeach</ul>@endif
        @foreach($validation['topology'] ?? [] as $network)<details><summary>Transformer #{{ $network['transformer_id'] }}: {{ count($network['nodes'] ?? []) }} connected nodes / {{ count($network['sections'] ?? []) }} surveyed sections</summary><div class="table-wrap"><table class="table mdb-review-table"><thead><tr><th>Section</th><th>Surveyed waypoint pair</th><th>Endpoint / geometry estimate (m)</th><th>Used length (m)</th></tr></thead><tbody>@foreach($network['sections'] ?? [] as $edge)<tr><td><a href="{{ route('mdb-workflow.show', [$batch, 'transformer_id'=>$network['transformer_id']]) }}#section-{{ $edge['section_id'] }}">#{{ $edge['section_id'] }}</a></td><td>Waypoint #{{ $edge['start_waypoint_id'] }} &rarr; #{{ $edge['end_waypoint_id'] }}</td><td>{{ isset($edge['estimated_length_m']) ? number_format($edge['estimated_length_m'], 2) : 'Unresolved' }}</td><td>{{ isset($edge['length_m']) ? number_format($edge['length_m'], 2) : 'Unresolved' }}<small>{{ str($edge['length_kind'])->replace('_', ' ')->title() }}</small></td></tr>@endforeach</tbody></table></div></details>@endforeach
    </section>
    <section class="card" id="review"><h2>Submission and verifier decisions</h2><p class="mdb-note">Every decision identifies its data revision. Editing approved values invalidates approval and supersedes the earlier exports.</p>
        @can('mdb-workflow.upload')@if(in_array($batch->status, ['draft','returned'], true))<form method="POST" action="{{ route('mdb-workflow.transition', $batch) }}">@csrf<input type="hidden" name="revision" value="{{ $batch->revision }}"><input type="hidden" name="action" value="submit"><div class="mdb-fields"><label class="mdb-span-all">Survey submission comment<textarea name="comment" maxlength="4000" rows="2"></textarea></label></div><div class="mdb-form-actions"><button class="btn btn-primary">Submit survey sources</button></div></form>@endif @endcan
        @can('mdb-workflow.edit')@if(in_array($batch->status, ['draft','submitted','returned'], true))<form method="POST" action="{{ route('mdb-workflow.transition', $batch) }}">@csrf<input type="hidden" name="revision" value="{{ $batch->revision }}"><input type="hidden" name="action" value="review"><div class="mdb-fields"><label class="mdb-span-all">Data entry completion comment<textarea name="comment" maxlength="4000" rows="2"></textarea></label></div><div class="mdb-form-actions"><button class="btn btn-primary">Send entered network for verification</button></div></form>@endif @endcan
        @can('mdb-workflow.verify')<div class="mdb-decision"><form method="POST" action="{{ route('mdb-workflow.transition', $batch) }}">@csrf<input type="hidden" name="revision" value="{{ $batch->revision }}"><div class="mdb-fields"><label class="mdb-span-all">Verifier comment / rejection reason<textarea name="comment" required minlength="5" maxlength="4000" rows="3"></textarea></label></div><div class="mdb-form-actions"><button class="btn btn-light" name="action" value="comment">Record review comment</button>@if($batch->status === 'awaiting_verification')<button class="btn btn-danger" name="action" value="reject">Return for correction</button><button class="btn btn-success" name="action" value="approve" @disabled(!($validation['valid'] ?? false))>Approve current revision</button>@endif</div>@if(!($validation['valid'] ?? false))<small>Resolve the critical validation errors before final approval.</small>@endif</form></div>@endcan
        @forelse($batch->decisions->sortByDesc('created_at') as $decision)<article class="mdb-decision"><strong>{{ str($decision->decision)->replace('_', ' ')->title() }}</strong> &middot; Revision #{{ $decision->revision?->number }} &middot; {{ $decision->verifier?->name ?? 'Workflow user' }}<small>{{ $decision->created_at?->timezone('Asia/Karachi')->format('d M Y H:i') }} PKT</small><p>{{ $decision->comments }}</p></article>@empty<p class="mdb-note">No submission or verifier decisions have been recorded.</p>@endforelse
    </section>
    <section class="card" id="exports"><h2>MDB outputs and SynerGEE validation</h2>
        @if(!$workerConfigured)<div class="mdb-worker-note"><strong>MDB export worker not configured.</strong> The application can prepare and validate versioned export payloads. A genuine MDB requires the configured Access DAO/ACE worker, an approved clean template and successful readback.</div>@endif
        <p class="mdb-note">A generated MDB remains pending engineering acceptance until the Analysis Team records its checks in SynerGEE.</p>
        @can('mdb-workflow.export')<form method="POST" action="{{ route('mdb-workflow.exports.store', $batch) }}">@csrf<input type="hidden" name="revision" value="{{ $batch->revision }}"><div class="mdb-fields"><label>Export scope<select name="transformer_id"><option value="">Consolidated feeder (requires compatible mapping)</option>@foreach($batch->transformers as $transformer)<option value="{{ $transformer->id }}" @selected($selectedTransformer?->id === $transformer->id)>{{ $transformer->code }}</option>@endforeach</select></label><label>Template bound to approved revision<input value="{{ data_get($batch->approvedRevision?->snapshot, 'template.code', 'Approval required') }} v{{ data_get($batch->approvedRevision?->snapshot, 'template.version', '') }}" readonly><input type="hidden" name="template_id" value="{{ data_get($batch->approvedRevision?->snapshot, 'template.id', '') }}"><small>Changing the template requires renewed approval.</small></label></div><div class="mdb-form-actions"><button class="btn btn-primary" @disabled(!$batch->approved_revision_id)>Queue MDB export</button>@if(!$batch->approved_revision_id)<small>Final approval of this immutable revision is required.</small>@endif</div></form>@endcan
        @forelse($batch->exports->sortByDesc('created_at') as $export)<article class="row-card"><div class="row-card-head"><strong>Export #{{ $export->id }} &middot; {{ $export->transformer?->code ?? 'Consolidated feeder' }}</strong><span class="status mdb-status-{{ $export->status }}">{{ str($export->status)->replace('_', ' ')->title() }}</span></div><p class="mdb-note">Data revision #{{ $export->revision?->number }} &middot; Template {{ $export->template?->version ?? $export->template_version }} &middot; Mapping {{ $export->mapping_version }} &middot; Attempts {{ $export->attempts }} @if($export->generated_at)&middot; Generated {{ $export->generated_at->timezone('Asia/Karachi')->format('d M Y H:i') }} PKT @endif</p>
            @if($export->superseded_at)<p class="mdb-inline-error">Superseded: the source data or engineering configuration changed. Use an export from the latest approved revision.</p>@endif
            <div class="actions">@if($export->status === 'generated' && !$export->superseded_at)@can('mdb-workflow.export')<a class="btn btn-light" href="{{ route('mdb-workflow.exports.download', $export) }}">Download verified MDB</a>@endcan @endif
            @if(in_array($export->status, ['failed','worker_not_configured'], true) && !$export->superseded_at)@can('mdb-workflow.export')<form method="POST" action="{{ route('mdb-workflow.exports.retry', $export) }}">@csrf<button class="btn btn-sm btn-light">Retry export job</button></form>@endcan @endif</div>
            @if($export->output_sha256)<small class="mdb-code">Output SHA-256 {{ $export->output_sha256 }}</small>@endif
            @if($export->log)<details><summary>Exporter log and readback</summary><pre class="mdb-code">{{ $export->log }}</pre><pre class="mdb-code">{{ json_encode($export->readback, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) }}</pre></details>@endif
            @php
                $events = $export->validations->sortBy('id');
                $lastReturnedId = $events->where('status', 'returned')->last()?->id ?? 0;
                $checks = $events->where('id', '>', $lastReturnedId)->pluck('status')->all();
            @endphp
            <p class="mdb-note"><strong>Current analysis status:</strong> {{ $events->last() ? str($events->last()->status)->replace('_', ' ')->title() : 'Pending analysis in SynerGEE' }}.</p>
            <ul class="mdb-state-list">@foreach(['downloaded'=>'Downloaded','opened'=>'Opened in SynerGEE','connectivity_checked'=>'Connectivity checked','load_flow_checked'=>'Load flow checked','accepted'=>'Accepted'] as $status=>$label)<li data-complete="{{ in_array($status, $checks, true) ? 'true' : 'false' }}">{{ $label }}</li>@endforeach</ul>
            @foreach($export->validations->sortBy('created_at') as $check)<p class="mdb-note"><strong>{{ str($check->status)->replace('_', ' ')->title() }}</strong> &middot; {{ $check->analyst?->name }} &middot; {{ $check->created_at?->timezone('Asia/Karachi')->format('d M Y H:i') }} PKT @if($check->synergee_version)&middot; SynerGEE {{ $check->synergee_version }}@endif<br>{{ $check->comments }}</p>@endforeach
            @can('mdb-workflow.analyze')@if($export->status === 'generated' && !$export->superseded_at)<details><summary>Record SynerGEE validation result</summary><form method="POST" action="{{ route('mdb-workflow.analysis.store', $export) }}">@csrf<div class="mdb-fields"><label>Completed analysis step<select name="status" required>@foreach(['downloaded'=>'Downloaded','opened'=>'Opened successfully in SynerGEE','connectivity_checked'=>'Connectivity checked','load_flow_checked'=>'Load flow checked','accepted'=>'Accepted','returned'=>'Returned for correction'] as $status=>$label)<option value="{{ $status }}">{{ $label }}</option>@endforeach</select></label><label>SynerGEE version<input name="synergee_version" maxlength="60"></label><label class="mdb-span-all">Results / correction comments<textarea name="comments" required maxlength="4000" rows="3"></textarea></label><label class="mdb-span-all">Evidence reference<input name="evidence[reference]" maxlength="2000" placeholder="Report, test case, or authorized document reference"></label></div><div class="mdb-form-actions"><button class="btn btn-primary">Record analysis step</button><small>Acceptance requires the preceding checks to be recorded.</small></div></form></details>@endif @endcan
        </article>@empty<p class="empty">No export jobs created. MDB output counts appear separately from transformer record counts.</p>@endforelse
    </section>
</div>
@endsection
@push('styles')<link rel="stylesheet" href="{{ asset('css/mdb-workflow.css') }}">@endpush
@push('scripts')
@if($selectedTransformer)<script>window.mdbSectionCopyData = {{ \Illuminate\Support\Js::from($selectedTransformer->sections->mapWithKeys(fn ($section) => [$section->id => $section->only(['phases','conductors','equipment_type','equipment_ref','pole_class','pole_height','pole_height_unit'])])) }};</script>@endif
<script src="{{ asset('js/mdb-workflow.js') }}" defer></script>
@endpush
