@extends('layouts.app')
@section('title', $project->code.' MDB engineering configuration')
@section('content')
@php
    $settingsExample = ['frequency_hz'=>null, 'nominal_voltage_kv'=>null, 'conductor_library_revision'=>'', 'transformer_library_revision'=>'', 'mapping'=>['version'=>'synergee-reviewed-v1', 'reviewed_by'=>null, 'reviewed_at'=>null, 'table_values'=>['SAI_Control'=>(object) [], 'Node'=>(object) [], 'InstSection'=>(object) [], 'InstFeeders'=>(object) [], 'InstPrimaryTransformers'=>(object) [], 'Loads'=>(object) []], 'networks'=>(object) [], 'consolidated_supported'=>false]];
    $loadExample = ['method'=>'', 'evidence'=>'', 'reviewer'=>'', 'notes'=>'Customer counts remain separate from verified per-phase kW, kvar and kVA.'];
    $metadataExample = ['equipment_references'=>['conductors'=>[], 'transformers'=>[], 'configurations'=>[]], 'permitted_static_tables'=>[]];
    $pretty = fn ($value) => json_encode($value, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
@endphp
<div class="mdb-workflow">
    <div class="page-head"><div><span class="eyebrow">Administrator / engineering review</span><h1>{{ $project->code }} MDB configuration</h1><p>{{ $project->name }} &middot; Project settings revision {{ $configuration?->revision ?? 0 }}</p></div><a class="btn btn-light" href="{{ route('mdb-workflow.index') }}">MDB dashboard</a></div>
    <div class="mdb-summary"><span class="status {{ $configuration?->approved_by ? 'mdb-status-approved' : 'status-pending' }}">{{ $configuration?->approved_by ? 'Engineering approved' : 'Engineering review required' }}</span><p>Choose the projection, electrical settings, load method and equipment mapping explicitly. The sample's 60 Hz, 4.16 kV and Zone 43N values require engineering review.</p></div>
    <section class="card"><h2>Project engineering settings</h2><p class="mdb-note">Saving a configuration revision invalidates affected approvals and supersedes their previous MDB exports. Empty values in the example below are placeholders for reviewed inputs.</p>
        <form method="POST" action="{{ route('mdb-workflow.config.update', $project) }}">@csrf @method('PUT')<input type="hidden" name="revision" value="{{ $configuration?->revision ?? 0 }}">
            <div class="mdb-fields"><label>Survey two-digit-year window starts at<input name="entry_year_start" type="number" min="1800" max="9900" value="{{ old('entry_year_start', data_get($configuration?->settings, 'entry.two_digit_year_start')) }}" placeholder="2000"><small>Choose explicitly. 2000 means YY 00?99 = 2000?2099; 1970 means 1970?2069. Used when pasting complete waypoints.</small></label>
            <label>Verified survey pole-height unit<select name="entry_height_unit"><option value="">Unconfirmed</option><option value="ft" @selected(old('entry_height_unit', data_get($configuration?->settings, 'entry.pole_height_unit')) === 'ft')>Feet (ft)</option><option value="m" @selected(old('entry_height_unit', data_get($configuration?->settings, 'entry.pole_height_unit')) === 'm')>Metres (m)</option></select><small>Confirm once from the survey source. Saved row units remain intact.</small></label></div>
            <div class="mdb-fields"><label>Projected coordinate system EPSG code<input name="epsg" value="{{ old('epsg', $configuration?->epsg) }}" type="number" min="1000" max="999999"><small>Use an engineering approved projected CRS with metre units appropriate to this project's survey area. Original WGS84 positions are preserved.</small></label><div><strong>Configuration approval</strong><p class="mdb-note">{{ $configuration?->approved_at ? 'Approved '.$configuration->approved_at->timezone('Asia/Karachi')->format('d M Y H:i').' PKT' : 'No engineering approval recorded.' }}</p></div>
            <label class="mdb-span-all">Electrical settings and SynerGEE mapping (JSON)<textarea name="settings_json" class="mdb-json" rows="22" required spellcheck="false">{{ old('settings_json', $pretty($configuration?->settings ?? $settingsExample)) }}</textarea><small>Required settings: frequency_hz, nominal_voltage_kv, conductor_library_revision and transformer_library_revision. The mapping must specify reviewed table values and explicit source wiring for each transformer. Use docs/mdb/MAPPING.md to match the installed SynerGEE schema.</small></label>
            <label class="mdb-span-all">Documented load inputs / estimation method (JSON)<textarea name="load_assumptions_json" class="mdb-json" rows="7" required spellcheck="false">{{ old('load_assumptions_json', $pretty($configuration?->load_assumptions ?? $loadExample)) }}</textarea><small>Document measured inputs or the approved method and evidence. Per-category customer counts and per-phase demand are recorded and approved separately on each section.</small></label>
            <label class="mdb-span-all">Change reason and review evidence<textarea name="reason" minlength="5" maxlength="4000" rows="3" required>{{ old('reason') }}</textarea></label>
            <label class="mdb-check mdb-span-all"><input name="approved" value="1" type="checkbox" @checked(old('approved'))>I have engineering authorization and approve this projection, electrical configuration, documented load method and SynerGEE mapping for this project.</label></div>
            <div class="mdb-form-actions"><button class="btn btn-primary">Save configuration revision</button></div>
        </form>
    </section>
    <section class="card"><h2>Clean SynerGEE MDB templates</h2><p class="mdb-note">A template preserves the required Access schema and approved equipment references. Existing network and control records must be removed. A file containing the sample transformer network cannot be used as a clean template.</p>
        <div class="table-wrap"><table class="table mdb-table"><thead><tr><th>Template</th><th>SynerGEE target</th><th>Approval</th><th>Integrity</th></tr></thead><tbody>@forelse($templates as $template)<tr><td>{{ $template->code }} v{{ $template->version }}</td><td>{{ $template->synergee_version }}</td><td><span class="status {{ $template->active && $template->approved_by ? 'mdb-status-approved' : 'status-pending' }}">{{ $template->active && $template->approved_by ? 'Approved / active' : 'Pending review' }}</span><small>{{ $template->approved_at?->timezone('Asia/Karachi')->format('d M Y H:i') }}</small></td><td><small class="mdb-source-hash">SHA-256 {{ $template->sha256 }}</small></td></tr>@empty<tr><td colspan="4" class="empty">No genuine clean MDB templates registered.</td></tr>@endforelse</tbody></table></div>
        <details><summary>Register a versioned genuine MDB template</summary><form method="POST" enctype="multipart/form-data" action="{{ route('mdb-workflow.templates.store') }}">@csrf<div class="mdb-fields"><label>Clean Microsoft Access MDB<input name="template_file" type="file" accept=".mdb,application/x-msaccess" required></label><label>Template code<input name="code" maxlength="100" required></label><label>Template version<input name="version" maxlength="60" required></label><label>SynerGEE product / version<input name="synergee_version" maxlength="60" required placeholder="Matches SAI_Control Product exactly"></label><label class="mdb-span-all">Equipment references and permitted static tables (JSON)<textarea name="metadata_json" rows="11" class="mdb-json" spellcheck="false" required>{{ old('metadata_json', $pretty($metadataExample)) }}</textarea><small>List verified conductor, transformer and configuration IDs present in this template. Static tables must be explicitly allowed. The worker checks the hash, cleanliness, required schema and generated MDB readability.</small></label><label class="mdb-check mdb-span-all"><input name="approved" type="checkbox" value="1" required>I verified this clean template's target version, equipment references and permitted static tables and authorize its use.</label></div><div class="mdb-form-actions"><button class="btn btn-primary">Register approved template version</button></div></form></details>
    </section>
</div>
@endsection
@push('styles')<link rel="stylesheet" href="{{ asset('css/mdb-workflow.css') }}">@endpush
