@extends('layouts.app')
@section('title', 'Review MDB survey')
@section('content')
@php($active = $batch->transformers->firstWhere('id', (int) request('transformer_id')) ?? $batch->transformers->first())
<div class="mdb-workflow mdb-entry">
    @if($batch->staged_workflow)
    <section class="card"><h2>Survey data verification</h2><p>Status: {{ str($batch->survey_status)->replace('_', ' ')->title() }} · Operator: {{ $batch->entryOperator?->name ?? 'Pending' }} · Verifier: {{ $batch->surveyVerifier?->name ?? 'Pending' }} · Entry completed: {{ $batch->entry_completed_at ?? 'Pending' }} · Verified: {{ $batch->survey_verified_at ?? 'Pending' }}</p><p>{{ $batch->survey_remarks }}</p>
        @foreach($batch->sources as $source)<p><a href="{{ route('mdb-workflow.source', [$batch, $source]) }}" target="_blank">{{ strtoupper($source->kind) }}: {{ $source->original_name }}</a></p>@endforeach
        @if(in_array($batch->survey_status, ['entry','returned'], true))
        @can('mdb-workflow.edit')<form method="POST" action="{{ route('mdb-workflow.survey.decision', $batch) }}">@csrf<input type="hidden" name="revision" value="{{ $batch->revision }}"><input type="hidden" name="action" value="submit"><button class="btn btn-primary">Submit survey for verification</button></form>@endcan
        @elseif($batch->survey_status === 'awaiting_verification')
        @can('mdb-workflow.surveyVerify')<form method="POST" action="{{ route('mdb-workflow.survey.decision', $batch) }}">@csrf<input type="hidden" name="revision" value="{{ $batch->revision }}"><label>Remarks<textarea name="remarks" maxlength="10000"></textarea></label><button name="action" value="approve" class="btn btn-primary">Approve survey</button><button name="action" value="return" class="btn btn-light">Return for correction</button></form>@endcan
        @endif
        <details><summary>Survey approval history</summary><ul>@foreach($surveyHistory as $event)<li>{{ $event->created_at }} · {{ $event->user?->name ?? 'Deleted user' }} · {{ str($event->action)->after('mdb.survey_')->title() }} · {{ $event->reason }}</li>@endforeach</ul></details>
    </section>
    @endif
    <div class="page-head"><div><h1>Review &amp; save</h1><p>{{ $batch->feeder?->feeder_name }} · Batch #{{ $batch->id }} · Revision {{ $batch->revision }}</p></div><a class="btn btn-light" href="{{ route('mdb-workflow.show', [$batch, 'transformer_id'=>$active?->id]) }}">Back to entry</a></div>
    <nav class="mdb-tabs">@foreach($batch->transformers as $transformer)<a href="{{ route('mdb-workflow.review', [$batch, 'transformer_id'=>$transformer->id]) }}" @if($active?->id === $transformer->id) aria-current="page" @endif>{{ $transformer->code }}</a>@endforeach</nav>
    @if($active)
    <section class="card"><h2>{{ $active->code }} — transformer header</h2><dl class="entry-review-header"><div><dt>Capacity</dt><dd>{{ $active->capacity_kva ?? 'Not entered' }} kVA</dd></div>
        @foreach(['substation_name'=>'Substation','feeder_name'=>'Feeder','feeder_identifier'=>'Feeder code','division'=>'Division','subdivision'=>'Subdivision','subdivision_code'=>'Subdivision code','make'=>'Make','inspector'=>'Inspector','location'=>'Location','survey_date'=>'Survey date','mounting'=>'Mounting','service_category'=>'Service category'] as $key=>$label)<div><dt>{{ $label }}</dt><dd>{{ $active->header[$key] ?? 'Not entered' }}</dd></div>@endforeach
    </dl></section>
    <section class="card"><h2>All S/E rows for {{ $active->code }}</h2><div class="table-wrap"><table class="table entry-review-table"><thead><tr><th>Pair / S/E</th><th>Page / entry sequence</th><th>Group / date</th><th>GPS waypoint</th><th>R / Y / B / N</th><th>Phase</th><th>Type / pole</th><th>Consumers</th><th>Int</th><th>PV details</th></tr></thead><tbody>
        @forelse($active->entryRows as $row)<tr><td>{{ $row->pair_number }} / <strong>{{ $row->designation }}</strong></td><td>{{ $row->source_page ?? '—' }} / {{ $row->source_row ?? '—' }}</td><td>{{ $row->group_number ?? '—' }}<small>{{ $row->row_date?->format('d/m/Y') ?? '—' }}</small></td><td>{{ $row->composite_identifier ?? 'Legacy identity' }}<small>GPS: {{ $row->waypoint_reference ?? 'Not entered' }} ? GPX source #{{ $row->gpx_source_id ?? 'unresolved' }}</small></td><td>@foreach(['R','Y','B','N'] as $phase)<small>{{ $phase }}: {{ ($row->conductors[$phase] ?? null) === null ? 'Not entered' : ($row->conductors[$phase] === '' ? 'None' : $row->conductors[$phase]) }}</small>@endforeach</td><td>{{ \App\Services\Mdb\EntryLookups::phase($row->conductors)['display'] ?: '—' }}</td><td>{{ $row->equipment_type ?? '—' }} / {{ $row->pole_class ?? '—' }}<small>{{ $row->pole_height ?? '—' }} {{ $row->pole_height_unit ?? '(unit unconfirmed)' }}</small></td><td>@foreach(\App\Services\Mdb\EntryLookups::CONSUMERS as $category=>$label)<small>{{ strtoupper($category) }}: {{ $row->consumers[$category] ?? 'blank' }}</small>@endforeach</td><td>{{ $row->intersection ? '✓' : '—' }}</td><td>@foreach($row->pv_details ?? [] as $pv)<small>{{ $pv['reference'] ?? '—' }} · service {{ $pv['service_load_kw'] ?? '—' }} kW · capacity {{ $pv['installed_capacity_kw'] ?? '—' }} kW · {{ $pv['remarks'] ?? '' }}</small>@endforeach</td></tr>@empty<tr><td colspan="10">No new S/E rows. Existing section records remain in the saved network; use the advanced editor to review them.</td></tr>@endforelse
    </tbody></table></div>
    @php($activeIssues = collect($entryIssues)->where('transformer_id', $active->id))
    @if($activeIssues->isNotEmpty())<div class="entry-error-summary entry-review-issues"><strong>Resolve these entries before final submission</strong><ul>@foreach($activeIssues as $issue)<li>Page {{ $issue['source_page'] ?? '—' }}, row {{ $issue['source_row'] ?? '—' }}: {{ $issue['message'] }}</li>@endforeach</ul></div>@endif
    @can('mdb-workflow.edit')<form method="POST" action="{{ route('mdb-workflow.entry.review', $batch) }}">@csrf<input type="hidden" name="revision" value="{{ $batch->revision }}"><input type="hidden" name="transformer_id" value="{{ $active->id }}"><label class="mdb-check"><input name="confirmed" type="checkbox" value="1" required><span>I checked this transformer header and all its S/E rows against the PDF.</span></label><div class="mdb-form-actions"><button class="btn btn-primary" @disabled($activeIssues->isNotEmpty())>Review and save {{ $active->code }}</button><a class="btn btn-light" href="{{ route('mdb-workflow.show', [$batch, 'transformer_id'=>$active->id]) }}">Correct entries</a></div></form>@endcan
    </section>@endif
    <section class="card"><h2>Verification and MDB generation</h2><p class="mdb-note">{{ str($batch->status)->replace('_',' ')->title() }}. Saved draft rows remain available when you return to entry.</p>
        @can($batch->staged_workflow ? 'mdb-workflow.process' : 'mdb-workflow.edit')@if(in_array($batch->status,['draft','submitted','returned'],true))<form method="POST" action="{{ route('mdb-workflow.transition', $batch) }}">@csrf<input type="hidden" name="revision" value="{{ $batch->revision }}"><input type="hidden" name="action" value="review"><button class="btn btn-light" @disabled(count($entryIssues))>Submit network for export approval</button></form>@endif@endcan
        @if(!$workerConfigured)<p class="mdb-worker-note">MDB export worker not configured.</p>@endif
        @can($batch->staged_workflow ? 'mdb-workflow.generate' : 'mdb-workflow.export')<form method="POST" action="{{ route('mdb-workflow.exports.store', $batch) }}">@csrf<input type="hidden" name="revision" value="{{ $batch->revision }}"><input type="hidden" name="transformer_id" value="{{ $active?->id }}"><div class="mdb-form-actions"><button class="btn btn-primary" @disabled(!$batch->approved_revision_id)>Generate MDB{{ $active ? ' for '.$active->code : '' }}</button>@if(!$batch->approved_revision_id)<small>Verifier approval is required.</small>@endif</div></form>@endcan
        @foreach($batch->exports->sortByDesc('id') as $export)
        <p>Export #{{ $export->id }} — {{ $export->transformer?->code ?? 'Feeder' }} — {{ str($export->status)->replace('_',' ') }}
            @if($export->status === 'generated' && !$export->superseded_at)
                @can('mdb-workflow.export')<a href="{{ route('mdb-workflow.exports.download', $export) }}">Download MDB</a>@endcan
            @endif
        </p>
        @endforeach
        <details><summary>Requirements for the MDB verifier / administrator ({{ count($validation['errors']) }})</summary><ul class="mdb-issue-list">@foreach($validation['errors'] as $issue)<li>{{ $issue['message'] }} @if(isset($issue['source_page']))<small>Page {{ $issue['source_page'] }}, row {{ $issue['source_row'] ?? '—' }}</small>@endif</li>@endforeach</ul></details>
        <div class="mdb-form-actions"><a class="btn btn-light" href="{{ route('mdb-workflow.advanced', [$batch, 'transformer_id'=>$active?->id]) }}">Engineering, verification &amp; export details</a>@can('mdb-workflow.configure')<a class="btn btn-light" href="{{ route('mdb-workflow.config', $batch->project_id) }}">Administrator settings</a>@endcan</div>
    </section>
</div>
@endsection
@push('styles')<link rel="stylesheet" href="{{ asset('css/mdb-workflow.css') }}"><link rel="stylesheet" href="{{ asset('css/mdb-entry.css') }}">@endpush
