@extends('layouts.app')
@section('title','Teams & Assignments')
@section('content')
<div class="page-head"><div><h1>Teams & Assignments</h1><p>Maintain delivery teams, membership, and survey feeder allocation.</p></div></div>
<section class="grid period-grid">@foreach(['Survey Teams'=>$surveyTeams,'MDB Teams'=>$mdbTeams] as $label=>$teams)<div class="card"><h2>{{ $label }}</h2>@forelse($teams as $team)<div style="padding:10px 0;border-top:1px solid var(--line)"><strong>{{ $team->code }} · {{ $team->name }}</strong>@if(isset($team->organization))<div class="muted">{{ $team->organization->name }}</div>@endif<div class="muted">{{ $team->members->pluck('name')->join(', ') ?: 'No members' }}</div></div>@empty<p class="muted">None configured.</p>@endforelse</div>@endforeach</section>
<div class="grid period-grid"><form class="card" method="POST" action="{{ route('admin.teams.store') }}">@csrf<h2>Create team</h2><div class="field"><label>Type</label><select name="type"><option value="survey">Survey</option><option value="mdb">MDB</option></select></div><div class="field"><label>Project</label><select name="project_id">@foreach($projects as $project)<option value="{{ $project->id }}">{{ $project->name }}</option>@endforeach</select></div><div class="field"><label>Code</label><input name="code" required></div><div class="field"><label>Name</label><input name="name" required></div><button class="btn btn-primary" style="margin-top:14px">Create team</button></form>
<form class="card" method="POST" action="{{ route('admin.teams.member') }}">@csrf<h2>Assign member</h2><div class="field"><label>Team type</label><select name="type" id="member-type"><option value="survey">Survey</option><option value="mdb">MDB</option></select></div><div class="field"><label>Team ID</label><input inputmode="numeric" type="number" min="1" name="team_id" placeholder="Shown beside team in database order" required></div><div class="field"><label>User</label><select name="user_id">@foreach($users as $user)<option value="{{ $user->id }}">{{ $user->name }} · {{ $user->role->label() }}</option>@endforeach</select></div><label style="display:flex;gap:8px;margin-top:12px"><input type="checkbox" name="is_leader" value="1"> Survey team leader</label><button class="btn btn-primary" style="margin-top:14px">Assign member</button></form>
<form class="card" method="POST" action="{{ route('admin.teams.assign-feeder') }}">@csrf<h2>Assign survey feeder</h2><div class="field"><label>Feeder</label><select name="feeder_id">@foreach($feeders as $feeder)<option value="{{ $feeder->id }}">{{ $feeder->feeder_code }} · {{ $feeder->feeder_name }}</option>@endforeach</select></div><div class="field"><label>Survey team</label><select name="survey_team_id">@foreach($surveyTeams as $team)<option value="{{ $team->id }}">{{ $team->name }}</option>@endforeach</select></div><div class="field"><label>Start date</label><input type="date" name="start_date" value="{{ today()->toDateString() }}"></div><div class="field"><label>End date</label><input type="date" name="end_date"></div><div class="field"><label>Remarks</label><input name="remarks"></div><button class="btn btn-primary" style="margin-top:14px">Assign feeder</button></form></div>
<div class="section-title"><h2>Active feeder assignments</h2></div><div class="card table-wrap"><table class="table"><thead><tr><th>Feeder</th><th>Survey team</th><th>Start</th><th>End</th></tr></thead><tbody>@foreach($assignments as $assignment)<tr><td>{{ $assignment->feeder->feeder_code }}</td><td>{{ $assignment->surveyTeam->name }}</td><td>{{ $assignment->start_date->format('d M Y') }}</td><td>{{ $assignment->end_date?->format('d M Y') ?: 'Open' }}</td></tr>@endforeach</tbody></table></div>
@endsection
