@extends('layouts.app')
@section('title','Add Processing Progress')
@section('content')
<div class="page-head"><div><h1>Daily MDB Processing Progress</h1><p>{{ auth()->user()->organization?->name }} · only your active assignments are listed.</p></div><a class="btn btn-light" href="{{ route('processing.entries.index') }}">View history</a></div>
@if($assignments->isEmpty())
<div class="card" role="alert"><h2>No active processing assignments</h2><p>Creating MDB files does not automatically assign them to your organization. Ask a project manager or administrator to use Assign Work, select your organization, and assign the available MDB quantity.</p></div>
@else
<form class="card" method="POST" action="{{ route('processing.entries.store') }}">@csrf<div class="form-grid"><div class="field"><label>Date</label><input type="date" name="entry_date" max="{{ today()->toDateString() }}" value="{{ today()->toDateString() }}" required></div><div class="field"><label>Overall remarks</label><input name="remarks"></div></div><div class="section-title"><h2>Assignments progressed</h2><button class="btn btn-sm btn-light" type="button" data-add-row>+ Add assignment</button></div><div data-row-list><div class="row-card"><div class="row-card-head"><strong data-row-number></strong><button type="button" class="btn btn-sm btn-light" data-remove-row>Remove</button></div><div class="form-grid"><div class="field"><label>Assignment</label><select name="items[0][assignment_id]" required><option value="">Select assignment</option>@foreach($assignments as $assignment)<option value="{{ $assignment->id }}">{{ $assignment->feeder->feeder_code }} — {{ $assignment->remaining_quantity }} remaining</option>@endforeach</select></div><div class="field"><label>MDB processed today</label><input data-quantity inputmode="numeric" type="number" min="1" name="items[0][mdb_processed]" required></div><div class="field"><label>Output Drive link</label><input type="url" name="items[0][output_drive_url]"></div><div class="field"><label>Remarks</label><input name="items[0][remarks]"></div></div></div></div><div class="form-footer"><strong class="form-total">Total today: <span data-total>0</span></strong><button class="btn btn-primary">Save processing progress</button></div></form>
<template id="row-template"><div class="row-card"><div class="row-card-head"><strong data-row-number></strong><button type="button" class="btn btn-sm btn-light" data-remove-row>Remove</button></div><div class="form-grid"><div class="field"><label>Assignment</label><select name="items[0][assignment_id]" required><option value="">Select assignment</option>@foreach($assignments as $assignment)<option value="{{ $assignment->id }}">{{ $assignment->feeder->feeder_code }} — {{ $assignment->remaining_quantity }} remaining</option>@endforeach</select></div><div class="field"><label>MDB processed today</label><input data-quantity inputmode="numeric" type="number" min="1" name="items[0][mdb_processed]" required></div><div class="field"><label>Output Drive link</label><input type="url" name="items[0][output_drive_url]"></div><div class="field"><label>Remarks</label><input name="items[0][remarks]"></div></div></div></template>
@endif
@endsection
@if($assignments->isNotEmpty())
@push('scripts')@include('components.entry-repeater-script')@endpush
@endif
