@extends('layouts.app')
@section('title','Manage Hierarchy')
@section('content')
<div class="page-head"><div><h1>Project Hierarchy</h1><p>Create controlled master records from project down to grid station. Use CSV import for feeders.</p></div><a class="btn btn-light" href="{{ route('admin.master.index') }}">Back to feeders</a></div>
<div class="grid period-grid">
<form class="card" method="POST" action="{{ route('admin.hierarchy.projects.store') }}">@csrf<h2>New project</h2><div class="field"><label>Code</label><input name="code" required></div><div class="field"><label>Name</label><input name="name" required></div><div class="field"><label>Timezone</label><input name="timezone" value="Asia/Karachi" required></div><label style="display:flex;gap:8px;margin-top:12px"><input type="checkbox" name="processing_required" value="1" checked> Processing required</label><button class="btn btn-primary" style="margin-top:14px">Add project</button></form>
<form class="card" method="POST" action="{{ route('admin.hierarchy.circles.store') }}">@csrf<h2>New circle</h2><div class="field"><label>Project</label><select name="project_id">@foreach($projects as $project)<option value="{{ $project->id }}">{{ $project->name }}</option>@endforeach</select></div><div class="field"><label>Code</label><input name="code" required></div><div class="field"><label>Name</label><input name="name" required></div><button class="btn btn-primary" style="margin-top:14px">Add circle</button></form>
<form class="card" method="POST" action="{{ route('admin.hierarchy.divisions.store') }}">@csrf<h2>New division</h2><div class="field"><label>Project</label><select name="project_id">@foreach($projects as $project)<option value="{{ $project->id }}">{{ $project->name }}</option>@endforeach</select></div><div class="field"><label>Circle</label><select name="circle_id">@foreach($circles as $circle)<option value="{{ $circle->id }}">{{ $circle->name }}</option>@endforeach</select></div><div class="field"><label>Code</label><input name="code" required></div><div class="field"><label>Name</label><input name="name" required></div><button class="btn btn-primary" style="margin-top:14px">Add division</button></form>
<form class="card" method="POST" action="{{ route('admin.hierarchy.sub-divisions.store') }}">@csrf<h2>New sub-division</h2><div class="field"><label>Project</label><select name="project_id">@foreach($projects as $project)<option value="{{ $project->id }}">{{ $project->name }}</option>@endforeach</select></div><div class="field"><label>Division</label><select name="division_id">@foreach($divisions as $division)<option value="{{ $division->id }}">{{ $division->name }}</option>@endforeach</select></div><div class="field"><label>Code</label><input name="code" required></div><div class="field"><label>Name</label><input name="name" required></div><button class="btn btn-primary" style="margin-top:14px">Add sub-division</button></form>
<form class="card" method="POST" action="{{ route('admin.hierarchy.grid-stations.store') }}">@csrf<h2>New grid station</h2><div class="field"><label>Project</label><select name="project_id">@foreach($projects as $project)<option value="{{ $project->id }}">{{ $project->name }}</option>@endforeach</select></div><div class="field"><label>Sub-division</label><select name="sub_division_id">@foreach($subDivisions as $subDivision)<option value="{{ $subDivision->id }}">{{ $subDivision->name }}</option>@endforeach</select></div><div class="field"><label>Code</label><input name="code" required></div><div class="field"><label>Name</label><input name="name" required></div><button class="btn btn-primary" style="margin-top:14px">Add grid station</button></form>
</div>
<div class="section-title"><h2>Current hierarchy</h2></div>
<div class="card table-wrap"><table class="table"><thead><tr><th>Project</th><th>Circles</th><th>Divisions</th><th>Sub-divisions</th><th>Grid stations</th><th>Feeders</th></tr></thead><tbody>@foreach($projects as $project)<tr><td><strong>{{ $project->code }}</strong><br>{{ $project->name }}</td><td>{{ $circles->where('project_id',$project->id)->count() }}</td><td>{{ $divisions->where('project_id',$project->id)->count() }}</td><td>{{ $subDivisions->where('project_id',$project->id)->count() }}</td><td>{{ $grids->where('project_id',$project->id)->count() }}</td><td>{{ $project->feeders_count }}</td></tr>@endforeach</tbody></table></div>
<div class="grid period-grid"><div class="card"><h2>Circles</h2>@foreach($circles as $record)<p><strong>{{ $record->code }}</strong> · {{ $record->name }}<br><small class="muted">{{ $record->project->name }}</small></p>@endforeach</div><div class="card"><h2>Divisions</h2>@foreach($divisions as $record)<p><strong>{{ $record->code }}</strong> · {{ $record->name }}<br><small class="muted">{{ $record->circle->name }}</small></p>@endforeach</div><div class="card"><h2>Grid stations</h2>@foreach($grids as $record)<p><strong>{{ $record->code }}</strong> · {{ $record->name }}<br><small class="muted">{{ $record->subDivision->name }}</small></p>@endforeach</div></div>
@endsection
