@extends('layouts.app')
@section('title','Master Data')
@section('content')
<div class="page-head"><div><h1>HAZECO Master Data</h1><p>Hierarchy baseline, feeder quantities, storage links, and CSV import.</p></div><div class="actions"><a class="btn btn-light" href="{{ route('admin.hierarchy.index') }}">Manage hierarchy</a><a class="btn btn-light" href="{{ route('admin.master.template') }}">Download CSV template</a></div></div>
<section class="grid kpi-grid">@foreach(['Projects'=>'projects','Circles'=>'circles','Divisions'=>'divisions','Sub-divisions'=>'sub_divisions','Grid stations'=>'grids','Feeders'=>'feeders'] as $label=>$key)<div class="card kpi"><i class="kpi-accent"></i><div class="kpi-label">{{ $label }}</div><div class="kpi-value">{{ $counts[$key] }}</div></div>@endforeach</section>
<div class="card"><h2 style="margin-top:0">Import or update feeders</h2><p class="muted">Rows are matched by project code + feeder code. Valid rows import even when another row is rejected.</p><form method="POST" action="{{ route('admin.master.import') }}" enctype="multipart/form-data">@csrf<div class="form-grid"><div class="field"><label>CSV file</label><input type="file" name="file" accept=".csv,text/csv" required></div><div class="field" style="align-self:end"><button class="btn btn-primary">Import master data</button></div></div></form>@if(session('import_result') && count(session('import_result.errors')))<div class="alert alert-danger" style="margin-top:14px"><strong>Validation errors</strong><ul>@foreach(array_slice(session('import_result.errors'),0,20) as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif</div>
<div class="section-title"><h2>Feeders</h2><form><div class="field"><input name="q" value="{{ request('q') }}" placeholder="Search feeder code or name"></div></form></div>
<div class="card table-wrap"><table class="table"><thead><tr><th>Feeder</th><th>Hierarchy</th><th>Transformers</th><th>Processing</th><th>Status</th><th>Drive folders</th><th></th></tr></thead><tbody>@foreach($feeders as $feeder)<tr><td><strong>{{ $feeder->feeder_code }}</strong><br>{{ $feeder->feeder_name }}</td><td>{{ $feeder->circle->name }}<br><small>{{ $feeder->division->name }} · {{ $feeder->gridStation->name }}</small></td><td>{{ $feeder->total_transformers }}</td><td>{{ $feeder->processing_required ? 'Required' : 'Not required' }}</td><td><span class="status">{{ strtoupper($feeder->status->value) }}</span></td><td>@if($feeder->survey_drive_url)<a target="_blank" rel="noopener" href="{{ $feeder->survey_drive_url }}">Survey</a>@endif @if($feeder->mdb_drive_url) · <a target="_blank" rel="noopener" href="{{ $feeder->mdb_drive_url }}">MDB</a>@endif</td><td><a class="btn btn-sm btn-light" href="{{ route('admin.master.edit',$feeder) }}">Edit</a></td></tr>@endforeach</tbody></table></div>{{ $feeders->links() }}
@endsection
